README.md
app.rb
spec/features/app_spec.rb
spec/fixtures/v1/amazon/regions.xml
spec/fixtures/v1/amazon/servers/types.xml
spec/fixtures/v1/images/states.xml
spec/fixtures/v1/providers.xml

Added APIs to allow users to query for available metadata
/v1/providers.?ext? - user can query Pint via REST api consistent with existing queries for a list of known providers/frameworks
/v1/:provider/regions.?ext? - user can query Pint via REST api consistent with existing queries for a list of known regions
/v1/:provider/images/states.?.ext? - user can query Pint via REST api consistent with existing queries for a list of states
/v1/:provider/servers/types.?ext? - user can query Pint via REST api consistent with existing queries for a list of server types
Added the tests for the new APIs
Modified README.md to add new APIs and also instructions to setup Development environment

Add metadata requests to pint API (CSE-20)

---

publicCloudInfo-server.conf.template

It should be /srv/www/publicCloudInfo-server/public instead of
/srv/www/publicCloudInfoSrv/public, according to
https://github.com/SUSE-Enceladus/public-cloud-info-service/blob/master/publicCloudInfo-server.spec#L55

Fix DocumentRoot path

---

app.rb
spec/features/app_spec.rb

As a developer of a web application that consumes _pint_ data, I require the API to implement Cross-Origin Resource Sharing (CORS).
As the _pint_ service is read-only, there's no risk in any web client consuming it (e.g. a client cannot be 'tricked' into pushing bad data, as nothing can be pushed), and credentials are not used, CORS can be enabled without limitation using a wildcard header: `Access-Control-Allow-Origin: *`, as defined in https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin .

Enable CORS requests from anywhere.

---

app.rb
spec/fixtures/framework-microsoft.xml
spec/fixtures/frameworks.xml

Azure is often inconsistent in its naming scheme for regions. In order to fix this issue, Added an alternate name under every region in microsoft.xml and updated the server code to implement this change.

apply azure region naming to the regions api (CSE-48)

---

next_generation/app.py

Existing pint API uses status 301 for redirect and no body.
However, pint-ng/flask redirect uses 302 as default status
code and the following in the body:
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Redirecting...</title>
<h1>Redirecting...</h1>
<p>You should be redirected automatically to target URL:
<a href="https://www.suse.com/solutions/public-cloud/">
https://www.suse.com/solutions/public-cloud/</a>.
If not click the link.
```
This change is to match the behavior of pint-ng with
the current pint api
Also the updated the catch_all with response with
no body to match the current pint behavior.

Match redirect behavior

---

next_generation/pint_server/tests/unit/test_app.py

The commented tests that are being cleaned up are
already covered in functional tests.

clean up unittests

---

pint_server/tests/loadtest/loadtest.py

Track the response times of the requests from the load generator and print a summary at the end

Summarize response times at end of load test

---

bin/orm_exporttopostgres
requirements.txt

Port the orm_exporttopostgres script to work with the new pint_server
implementation.
To use it you should clone the pint-data repo, that contains the XML
data to be import, beside the public-cloud-info-service; the script
will automatically look for the pint-data repo relative to it's own
location in the public-cloud-info-service/bin directory.
Run it by specifying the necessary command line arguments, e.g.
% bin/orm_exporttopostgres --host ${POSTGRES_HOST} \
--password ${POSTGRES_PASSWORD}
--user ${POSTGRES_USER}
The script will create the database tables if not already created,
and will then import the XML content from the pint-data repo, either
as a full import if no data exists, or incrementally importing new
changes made since the last import.
For incremental updates, when updating …

Add orm_exporttopostgres to bin/

---

bin/run_standalone.sh
pint_server/app.py

1. if 'changeinfo' is empty, don't return it
2. if 'urn' is empty, don't return it
3. for Alibaba and Oracle where we don't have any servers, we'll return
an empty list when query by server type in order to be backward
compatible
4. add mapping to map the original server types (i.e. smt, regionserver-sles,
regionserver-sap, etc) to the new server types (i.e. update and region)
in order to maintain backward compatibility

fix discrepancies between Pint and Pint NG

---

pint_server/__init__.py
pint_server/database.py
pint_server/models.py

Add support to the pint_server init_db() function to take optional
dbconfig, outputfile and echo parameters.
The dbconfig paramater allows a dictionary to be specified that
holds the required config settings needed to contruct the connection
URL string. If a dbconfig is specified then it's settings will be
used in preference to those specified in the environment. Otherwise
the DATABASE_URI env var setting will be used, or if that is not
specified then the individual POSTGRES_... env var settings will be
used.
If the outputfile parameter is specified it will be used to create
a DB specific logging service to log output from SQLAlchemy DB ops.
The echo parameter will be passed as the echo parameter when calling
create_engine() allowing control over the associated engine logging
verbosity. …

Implement init_db() enhancements in pint_server

---

requirements.txt

We don't want to recomplike the PostgreSQL DB driver on install as it
requires both gcc and postgresql12-server-devel packages.

use psycopg2-binary instead of psycopy2

---

pint_server/database.py

Try create_engine() with hide_parameters, and if it failed with a
TypeError and hide_paramaters in the exception message then try
again without the hide_parameters argument.

SLE 15 SP2 SQLAchemy version doesn't support hide_parameters

---

SUSE.rst
pint_server/__init__.py
pint_server/app.py
setup.cfg

Add an API to return the package version of the code to improve
deployability. The new API is
GET /package-version
and it will return something like this
{
"package version": "2.0.3"
}

Add an API to return the package version

---

pint_server/__init__.py
pint_server/data_update.py
pint_server/models.py
pint_server/pint_db_migrate/versions/8c5fc3cd9b18_microsoftimages_unique_constraint.py

Add a UniqueConstraint based upon the name and environment columns to
the MicrosoftImagesModel (microsoftimages) table definition.
Add a schema migration to upgrade the database to add the new unique
constraint to the microsoftimages.
Add a new class method to the PintBase class that returns the list of
defined unique constraints associated with a given table, or an empty
list if none are found.
Update the data_update.py IDENTITY_OVERRIDES mechanism to leverage the
new unique_constraints class method from PintBase when specifying an
override entry for the 'microsoftimages' table.
Report any duplicates found for the proposed unique constraint.
Any that are found will be reported as WARNING messages prior to the
attempt to add the new unique constraint.
Bump the version to 2.0.5
Closes: #97

Add unique constraint to MicrosoftImagesModel

---

pint_server/__init__.py
pint_server/app.py

The recent changes to add sequence based id fields to the Amazon,
Google and Microsoft servers tables, and the Microsoft images table
result in extraneous id fields appearing in the REST API request
results for these entities.
We can leverage the attr exclusion mechanism that is available in
the get_formatted_dict() helper function to avoid this problem.
Closes: #101

Exclude new primary key id fields from REST API request results

---

pint_server/__init__.py
pint_server/models.py
pint_server/pint_db_migrate/versions/14ae3b1b5e81_image_dates_validation.py

The 3 date fields in an images table entry should conform to the
following ordering rule, if not Null:
publishedon <= deprecatedon <= deletedon
The publishedon field cannot be Null, but the others may be Null if
the image hasn't transitioned to the associated state yet.
While no schema or data migration is involved we still add an Alembic
migration script which checks the existing DB content to ensure that
all images entries conform to this rule, reporting any problem entries
and failing with a ValueError exception if errors occur.
Bump pint_server version to 2.0.7.
Closes: #104

Add validation of image date fields

---

pint_server/data_update.py
pint_server/models.py
pint_server/schema_upgrade.py

When validating the publishedon, deprecatedon, and deletedon fields
we need to wait until published on has been set before trying to do
any validations against it.
Since the same validation is performed when triggered for any of the
three fields, it needs to support being called for deprecatedon or
deletedon before publishedon without failing, while performing all
of the validation when called for publishedon.
Also ensure that the schema_upgrade.py and data_update.py scripts
exit with a failed exit status if a failure occurs.
Closes: #104 (again), #107

Handle publishedon not yet set in data validator

---

bin/adhoc_db
pint_server/__init__.py
pint_server/models.py
pint_server/pint_db_migrate/versions/e937749e3f8b_servers_partial_unique_keys.py

A server is represented by a unique combination of IP addresses (and
optionally a region in the Microsoft case) so we want to ensure that
we can only add a given server once to the Amazon and Google servers
tables, and once per region to the Microsoft servers table.
In particular if we have a server with IPv4 and IPv6 addresses X and
Y respectively, we shouldn't be able to add more than one server for
for each of those addresses, so attempting to add a server with IPv4
address X, and another with IPv6 address Y, and a third server with
both addresses should fail.
To achieve this we can leverage partial unique indices to ensure that
a given address only occurs once, or once per region in the Microsoft
case.
Added a new 'adhoc_db' utility command in the bin directory that can
be used for …

Ensure uniqueness for the server entries in the servers tables

---

bin/adhoc_db
pint_server/models.py
pint_server/pint_db_migrate/versions/e937749e3f8b_servers_partial_unique_keys.py

Previously we defined new partial unique indices to ensure that IP
addresses were uniquely specified in the Amazon, Google and Microsoft
servers tables, though we allowed for them being unique per region in
the case of Microsoft.
However, we sometimes temporarily specify the update servers from an
existing region as the update servers for a newly created region until
the update infrastructure for the new region is in place.
To address this operational requirement we need to include the region
field in the partial unique indices for all servers tables, not just
the Microsoft servers table.
Update the adhoc_db duplicate_servers test to reflect the fact that
all servers tables, rather than just the Microsoft servers table,
should have the second region with the repeated IP address entry …

IP Addresses must be unique per region

---

pint_server/__init__.py
pint_server/data_update.py
pint_server/models.py
pint_server/pint_db_migrate/versions/ee82c541fae0_changeinfo_urls_end_in_slash.py

Add a validator that ensures that the changeinfo URLs end in a /.
Also add a data migration step which will make the same change to all
the existing changeinfo URLs in the database for all of the provider
images tables.
Update the data_update.py XML data extraction to automatically add a
trailing slash, if not present, to the changeinfo entries loaded from
the XML data, ensuring that future incremental data updates from XML
data don't incorrectly report data updates when processing older
entries that didn't end with '/'.
Bump version to 2.0.9.
Relates: #98

changeinfo URLs should end with a /

---

pint_server/app.py
pint_server/database.py
pint_server/tests/functional/test_function_app.py
pint_server/tests/unit/test_app.py

This PR adds a new route '/db-server-version which enables the ability to retrieve the psql server version, This is needed for pint-data-manager so it can dynamically determine the correct version of pg_dump to use. Currently pint-data-manager incorrectly is set for
`pg_dump = '/usr/lib/postgresql12/bin/pg_dump'`  
When testing upgrading the pint-server to PostgreSQL to version 14, an issue was found when running pint-data-manager due to the version mismatch between the psql server and pg_dump
Instead of just fixing this in pint-data-manager, it was suggested to make this a server function in case some other client would need access to the database server version.

Add a new route to retrieve the postgres server version

---

Dockerfile.aws
Makefile

AWS python3.9 image uses Amazon Linux 2 [1], which supports
native psycopg2-binary (postgre driver) out-of-the-box.
We no longer need to copying binaries around as we may run into
the risk of GLIBC incompatibilities.

Use aws python3.9 image instead of python3.6

---

pint_server/tests/unit/test_app.py

Server is returning 'database server version: 14.2' so the test
should look for that instead of 'postgreSQL server version: 14.2'.

Fix unit test for DB version

---

pint_server/app.py
pint_server/tests/functional/test_function_app.py
pint_server/tests/unit/mock_pint_data.py
pint_server/tests/unit/test_app.py
test-requirements.txt

Add the following new queries (both JSON and XML):
* Deletion date for images on a per provider basis, optionally
scoped to a specific region.
Will return an empty result for an image that has not yet been
deprecated, or the expected deletion date for an image in the
deprecated state, or the date on which an image was marked
deleted for images in the deleted state.
* Images that will be marked as deleted by a specific date, for
all providers, or for a specific provider, optionally scoped
to a specific region.
Will return a list of the currently deprecated images that will
be marked as deleted by the specified date.
To support these operations the dateutil.relativedelta module is
leveraged to generate an appopriate provider specific time delta
to be used in time calculations.
Deletion Date …

Add deletion date related queries

---

pint_server/app.py

To reduce the payload size for the /v1/{provider}/images requests
we can just provide a response that includes the active, inactive
and deprecated images.
If someone wants the deleted images they can explicitly request them
with a /v1/{provider}/images/deleted request.

Don't include deleted images in /v1/{provider}/images response

---

pint_server/app.py
pint_server/tests/unit/mock_pint_data.py

To ensure that images trimmed from oversized queries are the oldest ones, it is necessary to sort the image/state query by publishedon date. For consistency, sort the other image queries the same way.

Sort all image queries by publishedon date

---

pint_server/__init__.py

Update the version of the pint-server to 2.0.14 to enable releasing the sorting fix for the deleted image data.

Update pint-server to version 2.0.14

---

pint_server/app.py
pint_server/tests/unit/test_app.py

Change the default maximum payload size to 5MB. But it can be overwritten via environment variable MAX_PAYLOAD_SIZE.

Make MAX_PAYLOAD_SIZE configurable

---

.github/workflows/ci-workflow.yml
bin/create_dev_venv.sh
bin/create_test_venv.sh

Update the standard CI workflow job definition to target the latest ubuntu runner type.
Rename CI workflow jobs to reflect that they are running tests rather than building.
Create a duplicate job definition for legacy python versions that targets ubuntu-20.04, that is disabled under GitHub Actions runs, but still available to be tested locallly using nektos/act or the gh act extension.
Note that for versions of Python greater that 3.11 testing fails due to incompatible requirements.txt and test-requirements.txt package versions; these versions have been disabled until that issue has been addressed.
Ensure that the PATH is setup appropriately when using runners that run as a non-root user.
Update checkout and setup-python action versions to latest.
Ensure that the dev and test venv …

Update GitHub Actions CI workflow to use ubuntu-latest

---

SUSE.rst
package/python-PintServer.spec
requirements.txt
setup.cfg

Implementing bumpversion
Adding python-pintserver.spec file under package folder
Update the package versions in requirements.txt so that it works for Python 3.12 and 3.12+

Python 3.11 upgrade enhancements
